---
layout : article
title: "jupyter notebook에서 Cannot assign requested address 문제 해결하기 "
aside:
  toc: true
tags: Computer
category : Computer
author: melonicedlatte
published : True
hellogohn_num : 289
key : 2018-05-22-134429
--- 

<pre style="font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 11.9px; margin-bottom: 16px; word-wrap: normal; padding: 16px; line-height: 1.45; background-color: rgb(246, 248, 250); border-radius: 3px; color: rgb(36, 41, 46);"><code style="font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 11.9px; margin: 0px; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; border-radius: 3px; word-break: normal; white-space: pre; border: 0px; display: inline; overflow: visible; line-height: inherit; word-wrap: normal;">Traceback (most recent call last):                                                                                                                                                                                            
  File "/usr/local/bin/jupyter-notebook", line 11, in &lt;module&gt;                                                                                                                                                                
    sys.exit(main())                                                                                                                                                                                                          
  File "/usr/local/lib/python3.4/dist-packages/jupyter_core/application.py", line 267, in launch_instance                                                                                                                     
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)                                                                                                                                                        
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 657, in launch_instance                                                                                                                 
    app.initialize(argv)                                                                                                                                                                                                      
  File "&lt;decorator-gen-7&gt;", line 2, in initialize                                                                                                                                                                             
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 87, in catch_config_error                                                                                                               
    return method(app, *args, **kwargs)                                                                                                                                                                                       
  File "/usr/local/lib/python3.4/dist-packages/notebook/notebookapp.py", line 1296, in initialize                                                                                                                             
    self.init_webapp()                                                                                                                                                                                                        
  File "/usr/local/lib/python3.4/dist-packages/notebook/notebookapp.py", line 1120, in init_webapp                                                                                                                            
    self.http_server.listen(port, self.ip)                                                                                                                                                                                    
  File "/usr/local/lib/python3.4/dist-packages/tornado/tcpserver.py", line 142, in listen                                                                                                                                     
    sockets = bind_sockets(port, address=address)                                                                                                                                                                             
  File "/usr/local/lib/python3.4/dist-packages/tornado/netutil.py", line 197, in bind_sockets                                                                                                                                 
    sock.bind(sockaddr)                                                                                                                                                                                                       
OSError: [Errno 99] Cannot assign requested address </code></pre><p>jupyter 를 docker를 이용하여 구동할 때,&nbsp;Cannot assign requested address 문제가 생겼다.&nbsp;</p><p>port 문제인 것 같은데, 아래의 명령어를 통해 해결했다.&nbsp;</p><blockquote>jupyter notebook --ip=0.0.0.0 --port=8080</blockquote><p><br></p>